<template>
    <header class="main-header" >
        <a href="./accueil" class="logo">
            <span class="logo-mini"><b>J</b>DR</span>
            <span class="logo-lg"><b>Jeu</b> de rôle</span>
        </a>
        <nav class="navbar navbar-static-top" style="height : 50px;">
            <a href="#" class="sidebar-toggle" role="button">
                <span class="sr-only">Toggle navigation</span>
            </a>
            <div class="navbar-custom-menu">
                <ul class="nav navbar-nav">
                    <li>
                        <a href="/"><i class="fa fa-power-off"></i></a>
                    </li>
                </ul>
            </div>
        </nav>
    </header>
</template>

<script>
export default {
  name: 'Navbar'
}
</script>
